# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0005_add_extended_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiv2client',
            name='oauth_client',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiv2_client', to='apiv2.ExtendedApplication'),
        )
    ]
