# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oauth2_provider', '0006_auto_20171214_2232'),
        ('apiv2', '0006_remap_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='apiv2.ExtendedApplication')
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='apiv2.ExtendedApplication')
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='apiv2.ExtendedApplication')
        ),
    ]

    def __init__(self, name, app_label):
        super(Migration, self).__init__(name, app_label)
        self.app_label = 'oauth2_provider'
